[package]
name = "hello_wasm"
version = "0.0.1"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Document", "HtmlElement"] }


[lib]
crate-type = ["cdylib"]
